server:
  port: 8081
spring:
  application:
    name: PURCHASE-SERVICE
  redis:
    host: 127.0.0.1
    port: 6379

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/purchase_service
    username: postgres
    password: root
  kafka:
   producer:
    bootstrap-servers: 127.0.0.1:9092
    producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
   topic:name: wallet_topics

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

conversionRate: 1
rewardThreshold: 100
customer:
  client:
    uri: http://localhost:8082/api/customer


